package com.xiaoaitouch.mom.dao.babychange;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BABY_CHANGE.
 */
public class BabyChange {

    private Long id;
    private String week;
    private String height;
    private String weight;
    private String tips;

    public BabyChange() {
    }

    public BabyChange(Long id) {
        this.id = id;
    }

    public BabyChange(Long id, String week, String height, String weight, String tips) {
        this.id = id;
        this.week = week;
        this.height = height;
        this.weight = weight;
        this.tips = tips;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWeek() {
        return week;
    }

    public void setWeek(String week) {
        this.week = week;
    }

    public String getHeight() {
        return height;
    }

    public void setHeight(String height) {
        this.height = height;
    }

    public String getWeight() {
        return weight;
    }

    public void setWeight(String weight) {
        this.weight = weight;
    }

    public String getTips() {
        return tips;
    }

    public void setTips(String tips) {
        this.tips = tips;
    }

}
