package com.xiaoaitouch.mom.dao.babychange;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xiaoaitouch.mom.dao.babychange.BabyChange;

import com.xiaoaitouch.mom.dao.babychange.BabyChangeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig babyChangeDaoConfig;

    private final BabyChangeDao babyChangeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        babyChangeDaoConfig = daoConfigMap.get(BabyChangeDao.class).clone();
        babyChangeDaoConfig.initIdentityScope(type);

        babyChangeDao = new BabyChangeDao(babyChangeDaoConfig, this);

        registerDao(BabyChange.class, babyChangeDao);
    }
    
    public void clear() {
        babyChangeDaoConfig.getIdentityScope().clear();
    }

    public BabyChangeDao getBabyChangeDao() {
        return babyChangeDao;
    }

}
