package com.xiaoaitouch.mom.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xiaoaitouch.mom.dao.Symptoms;
import com.xiaoaitouch.mom.dao.UserInfo;
import com.xiaoaitouch.mom.dao.SportInfoModel;
import com.xiaoaitouch.mom.dao.SportCardModel;
import com.xiaoaitouch.mom.dao.HoroscopeModel;
import com.xiaoaitouch.mom.dao.ShareCardModel;
import com.xiaoaitouch.mom.dao.MWeightModel;
import com.xiaoaitouch.mom.dao.MSymptomModel;
import com.xiaoaitouch.mom.dao.MscModel;

import com.xiaoaitouch.mom.dao.SymptomsDao;
import com.xiaoaitouch.mom.dao.UserInfoDao;
import com.xiaoaitouch.mom.dao.SportInfoModelDao;
import com.xiaoaitouch.mom.dao.SportCardModelDao;
import com.xiaoaitouch.mom.dao.HoroscopeModelDao;
import com.xiaoaitouch.mom.dao.ShareCardModelDao;
import com.xiaoaitouch.mom.dao.MWeightModelDao;
import com.xiaoaitouch.mom.dao.MSymptomModelDao;
import com.xiaoaitouch.mom.dao.MscModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig symptomsDaoConfig;
    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig sportInfoModelDaoConfig;
    private final DaoConfig sportCardModelDaoConfig;
    private final DaoConfig horoscopeModelDaoConfig;
    private final DaoConfig shareCardModelDaoConfig;
    private final DaoConfig mWeightModelDaoConfig;
    private final DaoConfig mSymptomModelDaoConfig;
    private final DaoConfig mscModelDaoConfig;

    private final SymptomsDao symptomsDao;
    private final UserInfoDao userInfoDao;
    private final SportInfoModelDao sportInfoModelDao;
    private final SportCardModelDao sportCardModelDao;
    private final HoroscopeModelDao horoscopeModelDao;
    private final ShareCardModelDao shareCardModelDao;
    private final MWeightModelDao mWeightModelDao;
    private final MSymptomModelDao mSymptomModelDao;
    private final MscModelDao mscModelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        symptomsDaoConfig = daoConfigMap.get(SymptomsDao.class).clone();
        symptomsDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        sportInfoModelDaoConfig = daoConfigMap.get(SportInfoModelDao.class).clone();
        sportInfoModelDaoConfig.initIdentityScope(type);

        sportCardModelDaoConfig = daoConfigMap.get(SportCardModelDao.class).clone();
        sportCardModelDaoConfig.initIdentityScope(type);

        horoscopeModelDaoConfig = daoConfigMap.get(HoroscopeModelDao.class).clone();
        horoscopeModelDaoConfig.initIdentityScope(type);

        shareCardModelDaoConfig = daoConfigMap.get(ShareCardModelDao.class).clone();
        shareCardModelDaoConfig.initIdentityScope(type);

        mWeightModelDaoConfig = daoConfigMap.get(MWeightModelDao.class).clone();
        mWeightModelDaoConfig.initIdentityScope(type);

        mSymptomModelDaoConfig = daoConfigMap.get(MSymptomModelDao.class).clone();
        mSymptomModelDaoConfig.initIdentityScope(type);

        mscModelDaoConfig = daoConfigMap.get(MscModelDao.class).clone();
        mscModelDaoConfig.initIdentityScope(type);

        symptomsDao = new SymptomsDao(symptomsDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        sportInfoModelDao = new SportInfoModelDao(sportInfoModelDaoConfig, this);
        sportCardModelDao = new SportCardModelDao(sportCardModelDaoConfig, this);
        horoscopeModelDao = new HoroscopeModelDao(horoscopeModelDaoConfig, this);
        shareCardModelDao = new ShareCardModelDao(shareCardModelDaoConfig, this);
        mWeightModelDao = new MWeightModelDao(mWeightModelDaoConfig, this);
        mSymptomModelDao = new MSymptomModelDao(mSymptomModelDaoConfig, this);
        mscModelDao = new MscModelDao(mscModelDaoConfig, this);

        registerDao(Symptoms.class, symptomsDao);
        registerDao(UserInfo.class, userInfoDao);
        registerDao(SportInfoModel.class, sportInfoModelDao);
        registerDao(SportCardModel.class, sportCardModelDao);
        registerDao(HoroscopeModel.class, horoscopeModelDao);
        registerDao(ShareCardModel.class, shareCardModelDao);
        registerDao(MWeightModel.class, mWeightModelDao);
        registerDao(MSymptomModel.class, mSymptomModelDao);
        registerDao(MscModel.class, mscModelDao);
    }
    
    public void clear() {
        symptomsDaoConfig.getIdentityScope().clear();
        userInfoDaoConfig.getIdentityScope().clear();
        sportInfoModelDaoConfig.getIdentityScope().clear();
        sportCardModelDaoConfig.getIdentityScope().clear();
        horoscopeModelDaoConfig.getIdentityScope().clear();
        shareCardModelDaoConfig.getIdentityScope().clear();
        mWeightModelDaoConfig.getIdentityScope().clear();
        mSymptomModelDaoConfig.getIdentityScope().clear();
        mscModelDaoConfig.getIdentityScope().clear();
    }

    public SymptomsDao getSymptomsDao() {
        return symptomsDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public SportInfoModelDao getSportInfoModelDao() {
        return sportInfoModelDao;
    }

    public SportCardModelDao getSportCardModelDao() {
        return sportCardModelDao;
    }

    public HoroscopeModelDao getHoroscopeModelDao() {
        return horoscopeModelDao;
    }

    public ShareCardModelDao getShareCardModelDao() {
        return shareCardModelDao;
    }

    public MWeightModelDao getMWeightModelDao() {
        return mWeightModelDao;
    }

    public MSymptomModelDao getMSymptomModelDao() {
        return mSymptomModelDao;
    }

    public MscModelDao getMscModelDao() {
        return mscModelDao;
    }

}
