package com.xiaoaitouch.mom.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HOROSCOPE_MODEL.
 */
public class HoroscopeModel {

    private Long id;
    private String message;
    private String date;
    private Integer stars;
    private Long userId;
    private Integer cardType;
    private Integer dueDays;
    private Integer horoscope;
    private Long descTime;

    public HoroscopeModel() {
    }

    public HoroscopeModel(Long id) {
        this.id = id;
    }

    public HoroscopeModel(Long id, String message, String date, Integer stars, Long userId, Integer cardType, Integer dueDays, Integer horoscope, Long descTime) {
        this.id = id;
        this.message = message;
        this.date = date;
        this.stars = stars;
        this.userId = userId;
        this.cardType = cardType;
        this.dueDays = dueDays;
        this.horoscope = horoscope;
        this.descTime = descTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Integer getStars() {
        return stars;
    }

    public void setStars(Integer stars) {
        this.stars = stars;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getCardType() {
        return cardType;
    }

    public void setCardType(Integer cardType) {
        this.cardType = cardType;
    }

    public Integer getDueDays() {
        return dueDays;
    }

    public void setDueDays(Integer dueDays) {
        this.dueDays = dueDays;
    }

    public Integer getHoroscope() {
        return horoscope;
    }

    public void setHoroscope(Integer horoscope) {
        this.horoscope = horoscope;
    }

    public Long getDescTime() {
        return descTime;
    }

    public void setDescTime(Long descTime) {
        this.descTime = descTime;
    }

}
