package com.xiaoaitouch.mom.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MSC_MODEL.
 */
public class MscModel {

    private Long id;
    private Long userId;
    private Integer isOk;
    private String message;
    private String date;

    public MscModel() {
    }

    public MscModel(Long id) {
        this.id = id;
    }

    public MscModel(Long id, Long userId, Integer isOk, String message, String date) {
        this.id = id;
        this.userId = userId;
        this.isOk = isOk;
        this.message = message;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getIsOk() {
        return isOk;
    }

    public void setIsOk(Integer isOk) {
        this.isOk = isOk;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

}
