package com.xiaoaitouch.mom.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MWEIGHT_MODEL.
 */
public class MWeightModel {

    private Long id;
    private Long userId;
    private String weight;
    private String date;

    public MWeightModel() {
    }

    public MWeightModel(Long id) {
        this.id = id;
    }

    public MWeightModel(Long id, Long userId, String weight, String date) {
        this.id = id;
        this.userId = userId;
        this.weight = weight;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getWeight() {
        return weight;
    }

    public void setWeight(String weight) {
        this.weight = weight;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

}
