package com.xiaoaitouch.mom.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SEARCH_HISTORY.
 */
public class SearchHistory {

    private Long id;
    private String keyword;
    private Long createTime;

    public SearchHistory() {
    }

    public SearchHistory(Long id) {
        this.id = id;
    }

    public SearchHistory(Long id, String keyword, Long createTime) {
        this.id = id;
        this.keyword = keyword;
        this.createTime = createTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

}
