package com.xiaoaitouch.mom.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.xiaoaitouch.mom.dao.SportCardModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SPORT_CARD_MODEL.
*/
public class SportCardModelDao extends AbstractDao<SportCardModel, Long> {

    public static final String TABLENAME = "SPORT_CARD_MODEL";

    /**
     * Properties of entity SportCardModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Date = new Property(1, String.class, "date", false, "DATE");
        public final static Property SportMessage = new Property(2, String.class, "sportMessage", false, "SPORT_MESSAGE");
        public final static Property UserId = new Property(3, Long.class, "userId", false, "USER_ID");
        public final static Property CardType = new Property(4, Integer.class, "cardType", false, "CARD_TYPE");
        public final static Property DueDays = new Property(5, Integer.class, "dueDays", false, "DUE_DAYS");
        public final static Property DescTime = new Property(6, Long.class, "descTime", false, "DESC_TIME");
    };


    public SportCardModelDao(DaoConfig config) {
        super(config);
    }
    
    public SportCardModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SPORT_CARD_MODEL' (" + //
                "'ID' INTEGER PRIMARY KEY ," + // 0: id
                "'DATE' TEXT," + // 1: date
                "'SPORT_MESSAGE' TEXT," + // 2: sportMessage
                "'USER_ID' INTEGER," + // 3: userId
                "'CARD_TYPE' INTEGER," + // 4: cardType
                "'DUE_DAYS' INTEGER," + // 5: dueDays
                "'DESC_TIME' INTEGER);"); // 6: descTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SPORT_CARD_MODEL'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SportCardModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(2, date);
        }
 
        String sportMessage = entity.getSportMessage();
        if (sportMessage != null) {
            stmt.bindString(3, sportMessage);
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(4, userId);
        }
 
        Integer cardType = entity.getCardType();
        if (cardType != null) {
            stmt.bindLong(5, cardType);
        }
 
        Integer dueDays = entity.getDueDays();
        if (dueDays != null) {
            stmt.bindLong(6, dueDays);
        }
 
        Long descTime = entity.getDescTime();
        if (descTime != null) {
            stmt.bindLong(7, descTime);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SportCardModel readEntity(Cursor cursor, int offset) {
        SportCardModel entity = new SportCardModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // date
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // sportMessage
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // userId
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // cardType
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // dueDays
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6) // descTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SportCardModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDate(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSportMessage(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUserId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setCardType(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setDueDays(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setDescTime(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SportCardModel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SportCardModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
