package com.xiaoaitouch.mom.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SPORT_INFO_MODEL.
 */
public class SportInfoModel {

    private Long id;
    private Long userId;
    private String date;
    private Float time;
    private Integer steps;
    private String message;

    public SportInfoModel() {
    }

    public SportInfoModel(Long id) {
        this.id = id;
    }

    public SportInfoModel(Long id, Long userId, String date, Float time, Integer steps, String message) {
        this.id = id;
        this.userId = userId;
        this.date = date;
        this.time = time;
        this.steps = steps;
        this.message = message;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Float getTime() {
        return time;
    }

    public void setTime(Float time) {
        this.time = time;
    }

    public Integer getSteps() {
        return steps;
    }

    public void setSteps(Integer steps) {
        this.steps = steps;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

}
