package com.xiaoaitouch.mom.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SPORT_CARD_MODEL.
 */
public class SportCardModel {

    private Long id;
    private String date;
    private String sportMessage;
    private Long userId;
    private Integer cardType;
    private Integer dueDays;
    private Long descTime;

    public SportCardModel() {
    }

    public SportCardModel(Long id) {
        this.id = id;
    }

    public SportCardModel(Long id, String date, String sportMessage, Long userId, Integer cardType, Integer dueDays, Long descTime) {
        this.id = id;
        this.date = date;
        this.sportMessage = sportMessage;
        this.userId = userId;
        this.cardType = cardType;
        this.dueDays = dueDays;
        this.descTime = descTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getSportMessage() {
        return sportMessage;
    }

    public void setSportMessage(String sportMessage) {
        this.sportMessage = sportMessage;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getCardType() {
        return cardType;
    }

    public void setCardType(Integer cardType) {
        this.cardType = cardType;
    }

    public Integer getDueDays() {
        return dueDays;
    }

    public void setDueDays(Integer dueDays) {
        this.dueDays = dueDays;
    }

    public Long getDescTime() {
        return descTime;
    }

    public void setDescTime(Long descTime) {
        this.descTime = descTime;
    }

}
