package com.xiaoaitouch.mom.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SYMPTOMS.
 */
public class Symptoms implements java.io.Serializable {

    private Long id;
    private Integer type;
    private String symptom;
    private Long userId;

    public Symptoms() {
    }

    public Symptoms(Long id) {
        this.id = id;
    }

    public Symptoms(Long id, Integer type, String symptom, Long userId) {
        this.id = id;
        this.type = type;
        this.symptom = symptom;
        this.userId = userId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getSymptom() {
        return symptom;
    }

    public void setSymptom(String symptom) {
        this.symptom = symptom;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

}
