package com.xiaoaitouch.mom.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_INFO.
 */
public class UserInfo implements java.io.Serializable {

    private Long id;
    private Long userId;
    private String age;
    private String height;
    private String nickName;
    private String dueTime;
    private Double weight;
    private Integer mensesCircle;
    private String lastMensesTime;
    private String createTime;
    private String uniqueness;
    private String account;
    private String pwd;
    private String headPic;

    public UserInfo() {
    }

    public UserInfo(Long id) {
        this.id = id;
    }

    public UserInfo(Long id, Long userId, String age, String height, String nickName, String dueTime, Double weight, Integer mensesCircle, String lastMensesTime, String createTime, String uniqueness, String account, String pwd, String headPic) {
        this.id = id;
        this.userId = userId;
        this.age = age;
        this.height = height;
        this.nickName = nickName;
        this.dueTime = dueTime;
        this.weight = weight;
        this.mensesCircle = mensesCircle;
        this.lastMensesTime = lastMensesTime;
        this.createTime = createTime;
        this.uniqueness = uniqueness;
        this.account = account;
        this.pwd = pwd;
        this.headPic = headPic;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getHeight() {
        return height;
    }

    public void setHeight(String height) {
        this.height = height;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getDueTime() {
        return dueTime;
    }

    public void setDueTime(String dueTime) {
        this.dueTime = dueTime;
    }

    public Double getWeight() {
        return weight;
    }

    public void setWeight(Double weight) {
        this.weight = weight;
    }

    public Integer getMensesCircle() {
        return mensesCircle;
    }

    public void setMensesCircle(Integer mensesCircle) {
        this.mensesCircle = mensesCircle;
    }

    public String getLastMensesTime() {
        return lastMensesTime;
    }

    public void setLastMensesTime(String lastMensesTime) {
        this.lastMensesTime = lastMensesTime;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getUniqueness() {
        return uniqueness;
    }

    public void setUniqueness(String uniqueness) {
        this.uniqueness = uniqueness;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getPwd() {
        return pwd;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public String getHeadPic() {
        return headPic;
    }

    public void setHeadPic(String headPic) {
        this.headPic = headPic;
    }

}
